### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by pkill37** [pkill37/mybb-shetup#3]
I saw this article on Nettuts+ the other day and I thought it was worth mentioning.

http://net.tutsplus.com/tutorials/tools-and-tips/test-driving-shell-scripts

I'm fairly new to TDD myself, but I'm willing to learn. Given the nature of the script I'm sure there are a lot of corner cases in which it would just fail. I was hoping we could look into shunit2 and write some tests using it to automate the testing process.

**Comment by JoshHarmon** [comment]
I've never used unit testing before, but I too am curious about it a bit. I might play around with it tomorrow or something.

## 

Josh Harmon
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
