### ISSUE TITLE
Change how the download part works

### ISSUE THREAD

**Issue by pkill37** [pkill37/mybb-shetup#4]
The way the download part of the script works is not as I originally intended. Take a look at the `command_pick` and `download` functions. It basically checks if either git, wget, curl or lynx are available and downloads the branch using whichever command was available first.

The user should be asked if he wants to download the latest code from a branch on GitHub (master/stable/feature) or a specific version (1.6.5, 1.6.9, 1.6.10 or 1.8.1). If the user chose to download a branch it must use git to clone the repository, so as to fetch the latest code. If git isn't available, abort the script. And if the user chose a specific version like 1.6.5 the script should check if either wget or curl are available and download 1.6.5 from the tagged versions on GitHub using whichever command was available first.

Thoughts on this? I am also considering dropping lynx from the list of download methods. It's pointless. Almost any machine will have either wget or curl installed. Tons of other scripts rely solely on wget or curl to download stuff.

**Comment by JoshHarmon** [comment]
I don't really have any objection to removing lynx support from the script. Is there any tangible benefit to removing it? Otherwise it seems like it would just be good to have the support for niche cases.

If we can get people to type version codes properly  (or I guess we could strip the decimals), then the tagged downloads would work great, though many of those are older versions, and do we want to promote downloading old tagged versions?

**Comment by pkill37** [comment]
For the development version I think it may come in handy at some point. I'm not sure how often people need to test versions like 1.6.5, but it is a possibility. A possibility that I am willing to neglect, to be quite honest.

For production it is absolutely useless and we definitely shouldn't promote installation of older versions.

I guess it all comes down to deciding whether we should allow people to download older versions or not. If so, the download part needs to be changed. Otherwise we can maintain the current code, with a few minor adjustments perhaps. As for lynx I guess we can keep it.
