### ISSUE TITLE
pick_command not found

### ISSUE THREAD

**Issue by JoshHarmon** [pkill37/mybb-shetup#5]
Joshs-iMac:mybb-shetup josh$ ./mybb-shetup.sh

```
  __  __       ____  ____  
 |  \/  |     |  _ \|  _ \ 
 | \  / |_   _| |_) | |_) |
 | |\/| | | | |  _ <|  _ < 
 | |  | | |_| | |_) | |_) |
 |_|  |_|\__, |____/|____/ 
          __/ |            
         |___/             


Because free never tasted so good!
```

Welcome to mybb-shetup, the MyBB shell installer. This script will help you set up a copy of MyBB in a minute!
Press [ENTER] to continue... or press CTRL+C to quit.

Where would you like to install MyBB to (FULL PATH)? []/Users/josh/Desktop/mybb-shetup-test
The path you entered does not exist. Would you like to create it? [Y/n]Y
Creating /Users/josh/Desktop/mybb-shetup-test...
What branch would you like to download? [MASTER/stable/feature]feature
Do you want to install MyBB feature to ? [Y/n]Y
./mybb-shetup.sh: line 170: pick_command: command not found
Joshs-iMac:mybb-shetup josh$

**Comment by pkill37** [comment]
Forgot to change the reference to the function under `download()`. Fixing now.

**Comment by JoshHarmon** [comment]
I was just looking for it. Then I noticed that Cmd+F didn't even find the reference.. Then I saw your commit. :P

Tested as fixed for me.
