### ISSUE TITLE
Organize source tree

### ISSUE THREAD

**Issue by pkill37** [pkill37/mybb-shetup#7]
I was reading some bash stuff on best practices, portability and whatnot and came across a cool folder structure.

https://github.com/ymattw/sandbox/blob/master/sh/bash-best-practices.md#organize-your-source-tree

Any thoughts on this? I think it could be beneficial to split code into multiple files. It's clearly far more organized (better than what we have anyway). It also looks really pro. :P

On the other hand this no longer allows the script to be a single file download & run sort of thing. Not that it really matters, but it does lose that aspect to it.

It would also require some additional steps during installation to be able to run the script typing just `mybbshetup`. Upon cloning the repo, you would have to move the whole folder somewhere and symlink `/bin/run.sh` to `/usr/local/bin/mybbshetup` or something like that. Again, this doesn't really matter because installation is supposed to be a quick copy & paste from the readme.

**Comment by JoshHarmon** [comment]
I like that organization a lot more than what we have. It's like the (PHP/Actual) MyBB installer -- a mess of functions that generally only get called once.

I think what we could do is have a downloadable start file, which gets the MyBB Shetup files, gets permission, and moves them to /usr/bin . It could then execute the installer.

**Comment by pkill37** [comment]
Sounds good. That would certainly make things easier, while also allowing for the new folder structure.

We wouldn't even need to host the file ourselves. I think we can get away with a gist.

**Comment by JoshHarmon** [comment]
A gist should be perfect for this.
Gist started: https://gist.github.com/JoshH99/2eb82231482f5f746dc9
